services:
  app:
    build:
      context: sample/
      dockerfile: Dockerfile
    image: mocchi/sampleapp
    environment:
      APP_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./sample/app/:/root/app/
